import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "@/components/ui/provider";

import "./globals.css";
import Navbar from "@/components/NavBar/NavBar";
import { WordleProvider } from "@/context/WordleContext/WordleProvider";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/context/AuthContext/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wordle X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen overflow-hidden`}
      >
        <Provider>
          <AuthProvider>
            <WordleProvider>
              <Toaster />
              <Navbar />
              <main className="flex-1 overflow-y-auto">{children}</main>
            </WordleProvider>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
